"""added rental price

Revision ID: 516ddd11ffb3
Revises: fc42664f6308
Create Date: 2025-06-03 07:40:20.336478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516ddd11ffb3'
down_revision: Union[str, None] = 'fc42664f6308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('rental_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'rental_price')
    # ### end Alembic commands ###
