"""Your message

Revision ID: bb451654d9e1
Revises: b298c11da55e
Create Date: 2025-05-28 18:49:55.392685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb451654d9e1'
down_revision: Union[str, None] = 'b298c11da55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.add_column('rentals', sa.Column('end_date', sa.Date(), nullable=False))
    op.alter_column('rentals', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_column('rentals', 'duration_days')
    op.drop_column('rentals', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.add_column('rentals', sa.Column('duration_days', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'rentals', 'customers', ['customer_id'], ['id'])
    op.alter_column('rentals', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rentals', 'end_date')
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
